version: 0.2
phases:
  install:
    commands:
      - echo installing maven...
  build:
    commands:
      - echo building the justiceleague-tracker
      - mvn install
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'